"""`harness setup-project` — phase 2, setup.

Projects the validated task graph onto an issue tracker: one issue per task
file, the task's ``dir`` as a label, its ``phase`` as a milestone (spec section
4). Deliberately creates no folders in the target project — open question #9
settled that target directories come into existence in phase 3, when the
Developer agent first implements in one.

Three properties shape the code more than the API calls do:

*Approval before outward effect.* Issues are public, numbered, and awkward to
un-create, so the command prints a complete plan and stops for a yes. ``--yes``
exists for CI; ``--dry-run`` stops before the question.

*Re-runnable.* The command is expected to run again after the task files change.
A task already linked to an issue is never re-created; its issue is compared
against the task file and updated only where the two disagree. Labels a human
added by hand are kept — the harness adds, it does not prune.

*Failure is partial by default.* A rejected credential or an exhausted rate
limit dooms every remaining task, so the run aborts on it. One malformed issue
does not, so the other thirty-nine proceed and the failures are reported
together at the end. Either way every issue that *was* created is already in the
event log, so the next run resumes rather than duplicating.
"""

from __future__ import annotations

import argparse
import configparser
import hashlib
from typing import Any

from .. import taskfile, trackers
from ..paths import Project
from ..state import fold
from ..taskfile import TaskFile, TaskFileError
from ..trackers import (IssueSpec, RepoRef, TrackerError, TrackerItemError,
                        TrackerSystemicError)
from ..trackers.github import parse_remote, parse_repo_arg
from ._common import (CommandError, confirm, die, info, open_log, rel,
                      require_project, sync_state, warn)
from .chunk_specs import _validate_graph

MODES = ("new", "existing")

BODY_MARKER = "<!-- generated by ai-harness; edits are overwritten on the next setup-project run -->"

# Readable on both GitHub themes. The point is only that a given directory name
# always lands on the same colour, so labels look deliberate across projects.
LABEL_COLORS = ("0e8a16", "1d76db", "5319e7", "b60205", "d93f0b",
                "fbca04", "006b75", "0052cc", "e99695", "5843ad")


def add_parser(subparsers) -> None:
    p = subparsers.add_parser(
        "setup-project",
        help="create tracker issues, labels and milestones from the task files",
        description="Phase 2. Requires an approved spec and validated task files. "
                    "Prints a plan and asks before anything reaches the tracker. "
                    "Creates no directories in the target project.",
    )
    p.add_argument("mode", choices=MODES,
                   help="new: create the repository as well. "
                        "existing: use the repository already attached to this checkout.")
    p.add_argument("--repo", metavar="NAME",
                   help="new: name of the repository to create (or owner/name). "
                        "existing: override the repo inferred from git remote origin.")
    p.add_argument("--owner", metavar="ACCOUNT",
                   help="organisation to create the repository under "
                        "(default: the authenticated account)")
    visibility = p.add_mutually_exclusive_group()
    visibility.add_argument("--private", dest="private", action="store_const", const=True,
                            help="create the repository private (required for `new`)")
    visibility.add_argument("--public", dest="private", action="store_const", const=False,
                            help="create the repository public (required for `new`)")
    p.add_argument("--provider", default=trackers.DEFAULT_PROVIDER,
                   choices=trackers.providers(), help="issue tracker to use")
    p.add_argument("--dry-run", action="store_true",
                   help="print the plan and stop, without asking")
    p.add_argument("--yes", action="store_true",
                   help="skip the confirmation prompt (for non-interactive runs)")
    p.set_defaults(func=run, private=None)


# --------------------------------------------------------------------- pure

def _label_color(name: str) -> str:
    digest = hashlib.sha256(name.encode("utf-8")).hexdigest()
    return LABEL_COLORS[int(digest, 16) % len(LABEL_COLORS)]


def _milestone_title(phase: int) -> str:
    return f"Phase {phase}"


def _milestone_description(phase: int, task_count: int) -> str:
    return (f"Harness phase {phase} - {task_count} task(s) chunked from the approved "
            "spec. Managed by ai-harness.")


def _label_description(directory: str) -> str:
    return f"Harness task directory: {directory}"


def _topological_order(tasks: list[TaskFile]) -> list[TaskFile]:
    """Dependency-first order, so a dependency always has an issue number by the
    time a dependent's body needs to link to it."""
    by_id = {t.id: t for t in tasks}
    remaining = {t.id: set(t.depends_on) for t in tasks}
    ordered: list[TaskFile] = []
    while remaining:
        ready = sorted(tid for tid, deps in remaining.items() if not deps)
        if not ready:  # unreachable: _validate_graph rejects cycles first
            ordered.extend(by_id[tid] for tid in sorted(remaining))
            break
        for tid in ready:
            ordered.append(by_id[tid])
            remaining.pop(tid)
        for deps in remaining.values():
            deps.difference_update(ready)
    return ordered


def _issue_title(task: TaskFile) -> str:
    return f"{task.id}: {task.frontmatter['title']}"


def _issue_body(task: TaskFile, project: Project,
                dep_numbers: dict[str, int]) -> str:
    """Spec section 4: link back to the task file, embed acceptance_criteria as a
    checklist. Context and Task come along because an issue that only links
    elsewhere is not usable by the human who gets assigned it."""
    # Plain code, not a markdown link: a relative link in an issue body is not
    # reliably resolved, and a broken link is worse than a path you can copy.
    path = rel(task.path, project.root).replace("\\", "/")
    fm = task.frontmatter

    parts = [
        BODY_MARKER,
        "",
        f"**Task file:** `{path}`",
        f"**Start condition:** {fm['start_condition']}",
        f"**Done condition:** {fm['done_condition']}",
    ]

    context = task.section("Context")
    if context:
        parts += ["", "## Context", "", context]

    body = task.section("Task")
    if body:
        parts += ["", "## Task", "", body]

    parts += ["", "## Acceptance criteria", ""]
    parts += [f"- [ ] {c}" for c in fm["acceptance_criteria"]]

    if task.depends_on:
        parts += ["", "## Depends on", ""]
        for dep in task.depends_on:
            number = dep_numbers.get(dep)
            parts.append(f"- [ ] #{number} ({dep})" if number
                         else f"- [ ] {dep} (no issue yet)")

    if fm.get("inputs"):
        parts += ["", "## Inputs", ""]
        parts += [f"- `{i}`" for i in fm["inputs"]]

    return "\n".join(parts).rstrip() + "\n"


def _normalize(text: str) -> str:
    """GitHub returns bodies with CRLF; a line ending is not a drift."""
    return "\n".join(line.rstrip() for line in text.replace("\r\n", "\n").split("\n")).strip()


def _drift(issue, spec: IssueSpec) -> list[str]:
    """What differs between the live issue and what the task file now says.

    Labels compare as a subset, not equality: a label a human added is theirs,
    and reconciliation is not licence to strip it.
    """
    changes: list[str] = []
    if issue.title != spec.title:
        changes.append("title")
    if _normalize(issue.body) != _normalize(spec.body):
        changes.append("body")
    if not set(spec.labels) <= set(issue.labels):
        changes.append("labels")
    if spec.milestone and issue.milestone != spec.milestone:
        changes.append("milestone")
    return changes


def _parse_issue_ref(ref: str) -> tuple[str, RepoRef, int] | None:
    """``github:owner/name#42`` back into its parts."""
    provider, _, rest = ref.partition(":")
    repo_part, _, number = rest.partition("#")
    if not (provider and repo_part and number.isdigit()):
        return None
    parts = repo_part.split("/")
    if len(parts) != 2:
        return None
    return provider, RepoRef(parts[0], parts[1]), int(number)


def _repo_from_git_config(project: Project) -> RepoRef | None:
    """Read ``origin`` straight out of .git/config — no subprocess, no git needed."""
    config_path = project.root / ".git" / "config"
    if not config_path.is_file():
        return None
    parser = configparser.ConfigParser(strict=False, interpolation=None)
    try:
        parser.read(config_path, encoding="utf-8")
    except configparser.Error:
        return None
    for section in parser.sections():
        if section.replace('"', "").strip() == "remote origin":
            url = parser[section].get("url")
            return parse_remote(url) if url else None
    return None


# ----------------------------------------------------------------- pipeline

def _resolve_repo(args: argparse.Namespace, project: Project,
                  account: str) -> tuple[RepoRef, bool]:
    """Work out which repository to act on. Returns ``(repo, create_it)``."""
    if args.mode == "new":
        if not args.repo:
            die("`setup-project new` needs a repository name: --repo NAME "
                "(or --repo owner/name).\n"
                "Nothing is inferred from the directory name.")
        if args.private is None:
            die("`setup-project new` needs an explicit visibility: --private or --public.")

        ref = parse_repo_arg(args.repo)
        if ref is None:
            ref = RepoRef("", args.repo.strip())
        owner = args.owner or ref.owner or account
        if args.owner and ref.owner and args.owner != ref.owner:
            die(f"--owner {args.owner} conflicts with --repo {args.repo}.")
        if not ref.name:
            die(f"--repo {args.repo!r} is not a usable repository name.")
        return RepoRef(owner, ref.name), True

    if args.private is not None:
        die("--private/--public only applies to `setup-project new`; "
            "the harness does not change the visibility of an existing repository.")
    if args.owner:
        die("--owner only applies to `setup-project new`; "
            "use --repo owner/name to target an existing repository.")

    if args.repo:
        ref = parse_repo_arg(args.repo)
        if ref is None:
            die(f"--repo {args.repo!r} is not owner/name.")
        return ref, False

    ref = _repo_from_git_config(project)
    if ref is None:
        die("could not work out which repository to use.\n"
            f"No GitHub 'origin' remote found in {rel(project.root / '.git' / 'config', project.root)}.\n"
            "Pass --repo owner/name, or use `setup-project new` to create one.")
    return ref, False


def _known_links(state: dict[str, Any], tasks: list[TaskFile]) -> dict[str, str]:
    """Issue refs already recorded, from either place they are kept.

    The event log is authoritative; a task file carrying a ref the log has never
    seen is still honoured, because the alternative is creating a duplicate
    issue for a task that already has one.
    """
    links: dict[str, str] = {}
    for task in tasks:
        from_state = (state.get("tasks", {}).get(task.id) or {}).get("issue_ref")
        from_file = task.issue_ref
        if from_state and from_file and from_state != from_file:
            warn(f"{task.id}: event log says {from_state}, task file says {from_file}. "
                 "Using the event log.")
        ref = from_state or from_file
        if ref:
            links[task.id] = ref
    return links


def _print_plan(project: Project, args, repo: RepoRef, create_repo: bool,
                account: str, credential: str, tasks: list[TaskFile],
                links: dict[str, str], new_labels: list[str], new_milestones: list[str],
                repo_url: str | None) -> None:
    by_dir: dict[str, int] = {}
    for task in tasks:
        by_dir[task.dir] = by_dir.get(task.dir, 0) + 1

    to_create = [t for t in tasks if t.id not in links]
    to_check = [t for t in tasks if t.id in links]

    info("")
    info(f"Plan  ({args.mode})")
    info("")
    info(f"  tracker      {args.provider} as {account}   (credential from {credential})")
    if create_repo:
        info(f"  repository   {repo.full}   WILL BE CREATED, "
             f"{'private' if args.private else 'public'}")
    else:
        info(f"  repository   {repo.full}   {repo_url or ''}".rstrip())
    info(f"  tasks        {len(tasks)} across {len(by_dir)} director(ies): "
         + ", ".join(f"{d} ({n})" for d, n in sorted(by_dir.items())))
    info("")
    info(f"  labels       {len(new_labels)} to create"
         + (f": {', '.join(new_labels)}" if new_labels else " (all present)"))
    info(f"  milestones   {len(new_milestones)} to create"
         + (f": {', '.join(new_milestones)}" if new_milestones else " (all present)"))
    info(f"  issues       {len(to_create)} to create, "
         f"{len(to_check)} existing (updated only where they differ)")
    info("")
    for task in tasks:
        if task.id in links:
            info(f"    {task.id}  check   {links[task.id]}")
        else:
            info(f"    {task.id}  create  [{task.dir}] [{_milestone_title(task.phase)}] "
                 f"{task.frontmatter['title']}")
    info("")
    info("  No directories are created in the target project (spec open question #9).")


# ---------------------------------------------------------------------- run

def run(args: argparse.Namespace) -> int:
    project = require_project()
    log = open_log(project)
    state = fold(log)

    if state["spec"]["status"] != "approved":
        die("the spec is not approved yet.\n"
            "Run `harness review-specs` until it comes back clean, then "
            "`harness review-specs --approve`.")

    try:
        tasks = taskfile.load_all(project)
    except TaskFileError as exc:
        die(f"task files do not validate:\n{exc}")

    if not tasks:
        die(f"no task files under {rel(project.tasks, project.root)}.\n"
            "Run `harness chunk-specs` first.")

    _validate_graph([{"id": t.id, "depends_on": t.depends_on} for t in tasks])

    try:
        tracker, credential = trackers.get(args.provider, project)
        account = tracker.whoami()
        repo, create_repo = _resolve_repo(args, project, account)

        repo_url: str | None = None
        existing_labels: set[str] = set()
        existing_milestones: dict[str, int] = {}
        if not create_repo:
            repo_url = tracker.repo_url(repo)
            if repo_url is None:
                die(f"{repo.full} does not exist, or {account} cannot see it.\n"
                    "Check the name, or use `setup-project new` to create it.")
            existing_labels = tracker.labels(repo)
            existing_milestones = tracker.milestones(repo)
    except TrackerError as exc:
        raise CommandError(str(exc)) from exc

    links = _known_links(state, tasks)
    ordered = _topological_order(tasks)

    wanted_labels = sorted({t.dir for t in tasks})
    tasks_per_phase: dict[int, int] = {}
    for task in tasks:
        tasks_per_phase[task.phase] = tasks_per_phase.get(task.phase, 0) + 1
    wanted_milestones = [_milestone_title(p) for p in sorted(tasks_per_phase)]

    new_labels = [name for name in wanted_labels if name not in existing_labels]
    new_milestones = [title for title in wanted_milestones if title not in existing_milestones]

    _print_plan(project, args, repo, create_repo, account, credential, ordered,
                links, new_labels, new_milestones, repo_url)

    if args.dry_run:
        info("")
        info("--dry-run: nothing sent to the tracker.")
        return 0

    if not args.yes:
        info("")
        if not confirm(f"Apply this to {repo.full}?"):
            info("Aborted. Nothing was sent to the tracker.")
            return 1

    info("")
    return _apply(args, project, log, state, tracker, repo, create_repo, repo_url,
                  tasks_per_phase, wanted_labels, links, ordered)


def _apply(args, project: Project, log, state, tracker, repo: RepoRef,
           create_repo: bool, repo_url: str | None, tasks_per_phase: dict[int, int],
           wanted_labels: list[str], links: dict[str, str],
           ordered: list[TaskFile]) -> int:
    # Repository, labels and milestones all precede the issue loop and every
    # task depends on them, so any failure here is fatal regardless of kind.
    try:
        if create_repo:
            repo, url = tracker.create_repo(repo.name, owner=repo.owner,
                                            private=bool(args.private))
            info(f"Created repository {repo.full}  {url}")
        else:
            url = repo_url

        recorded = state.get("repo") or {}
        if recorded.get("full") != repo.full or recorded.get("provider") != args.provider:
            log.append("tracker.repo_linked", {
                "provider": args.provider, "repo": repo.full,
                "url": url, "created": create_repo,
            })

        created_labels = [name for name in wanted_labels
                          if tracker.ensure_label(repo, name, _label_color(name),
                                                  _label_description(name))]
        created_milestones = []
        for phase in sorted(tasks_per_phase):
            title = _milestone_title(phase)
            _, was_created = tracker.ensure_milestone(
                repo, title, _milestone_description(phase, tasks_per_phase[phase]))
            if was_created:
                created_milestones.append(title)

        if created_labels or created_milestones:
            log.append("tracker.metadata_synced", {
                "provider": args.provider, "repo": repo.full,
                "labels_created": created_labels,
                "milestones_created": created_milestones,
            })
            info(f"Labels created: {', '.join(created_labels) or 'none'}")
            info(f"Milestones created: {', '.join(created_milestones) or 'none'}")
    except TrackerError as exc:
        sync_state(project)
        raise CommandError(str(exc)) from exc

    numbers: dict[str, int] = {}
    for task_id, ref in links.items():
        parsed = _parse_issue_ref(ref)
        if parsed:
            numbers[task_id] = parsed[2]

    created: list[str] = []
    updated: list[str] = []
    unchanged: list[str] = []
    failures: list[tuple[str, str]] = []
    aborted: str | None = None

    for task in ordered:
        spec = IssueSpec(
            title=_issue_title(task),
            body=_issue_body(task, project, numbers),
            labels=[task.dir],
            milestone=_milestone_title(task.phase),
        )
        try:
            ref = links.get(task.id)
            if ref:
                outcome = _reconcile(tracker, repo, task, ref, spec, log, project)
                (updated if outcome else unchanged).append(task.id)
                if outcome:
                    info(f"  {task.id}  updated ({', '.join(outcome)})")
            else:
                issue = tracker.create_issue(repo, spec)
                new_ref = tracker.issue_ref(repo, issue.number)
                log.append("task.issue_linked", {
                    "task_id": task.id, "issue_ref": new_ref,
                    "url": issue.url, "title": issue.title,
                })
                # Record the number before touching the file: if the rewrite
                # fails, dependents still link to a real issue and the log
                # already knows this task is linked.
                links[task.id] = new_ref
                numbers[task.id] = issue.number
                _write_issue_ref(task, new_ref, project)
                created.append(task.id)
                info(f"  {task.id}  created #{issue.number}  {issue.url}")
        except TrackerItemError as exc:
            failures.append((task.id, str(exc)))
            warn(f"{task.id}: {exc}")
        except TrackerSystemicError as exc:
            aborted = str(exc)
            break

    state = sync_state(project)

    linked_all = not failures and aborted is None and all(t.id in links for t in ordered)
    if linked_all and state["phase"] == "setup":
        log.append("phase.changed", {"from": "setup", "to": "execution",
                                     "reason": "every task has a tracker issue"})
        state = sync_state(project)

    info("")
    info(f"Issues: {len(created)} created, {len(updated)} updated, "
         f"{len(unchanged)} already current")
    if failures:
        info("")
        info(f"{len(failures)} task(s) failed:")
        for task_id, message in failures:
            info(f"  {task_id}: {message}")
        info("Re-run `harness setup-project` to retry them; "
             "issues already created are not re-created.")
    if aborted:
        info("")
        info(f"Aborted: {aborted}")
        info(f"{len(created)} issue(s) were created before the failure and are "
             "recorded in the event log. Fix the cause and re-run to resume.")
        raise CommandError("setup stopped on a failure that would repeat for every "
                           "remaining task")

    info(f"phase: {state['phase']}")
    if failures:
        return 1
    info("")
    info("Next: harness run --dry-run   (see the phase 3 execution plan before anything runs)")
    return 0


def _reconcile(tracker, repo: RepoRef, task: TaskFile, ref: str, spec: IssueSpec,
               log, project: Project) -> list[str]:
    """Bring an existing issue back in line with its task file. Returns what changed."""
    parsed = _parse_issue_ref(ref)
    if parsed is None:
        raise TrackerItemError(f"issue reference {ref!r} is not parseable")
    _, ref_repo, number = parsed
    if ref_repo.full != repo.full:
        raise TrackerItemError(
            f"already linked to {ref}, which is a different repository than "
            f"{repo.full}; the harness will not move an issue between repositories")

    issue = tracker.get_issue(repo, number)
    if issue is None:
        raise TrackerItemError(
            f"linked issue #{number} no longer exists. Remove issue_ref from "
            f"{rel(task.path, project.root)} to have a new one created.")

    # Backfill the task file if only the log knew about the link.
    if task.issue_ref != ref:
        _write_issue_ref(task, ref, project)

    changes = _drift(issue, spec)
    if not changes:
        return []

    merged = IssueSpec(
        title=spec.title,
        body=spec.body,
        labels=sorted(set(spec.labels) | set(issue.labels)),
        milestone=spec.milestone,
    )
    tracker.update_issue(repo, number, merged)
    log.append("task.issue_reconciled", {
        "task_id": task.id, "issue_ref": ref, "changes": changes,
    })
    return changes


def _write_issue_ref(task: TaskFile, ref: str, project: Project) -> None:
    """Record the issue in the task file — validated before it reaches disk."""
    from .. import contracts
    from ..contracts import ContractViolation

    task.frontmatter["issue_ref"] = ref
    try:
        contracts.validate("task", task.frontmatter, project)
    except ContractViolation as exc:
        raise TrackerItemError(
            f"writing issue_ref would break the task contract for "
            f"{rel(task.path, project.root)}:\n{exc}") from exc
    task.save()
